services:
  mysql_db_weblog:
    container_name: mysql_db_weblog
    image: mysql:9.2.0
    restart: 'no'
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    
    volumes:
      - weblogData:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
   
  phpmyadmin:
    container_name: phpmyadmin_weblog
    image: phpmyadmin/phpmyadmin
    restart: 'no'
    env_file: ./.env
    environment:
      - PMA_HOST=mysql_db_weblog
      - PMA_PORT=3306
    ports:
      - 8080:80
    depends_on:
      - mysql_db_weblog

  redis:
    container_name: redis_db_weblog
    image: redis:7.4.1-alpine3.20
    env_file: ./.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}


volumes:
  weblogData: